### PR TITLE
Update CI workflow to reflect changes to downstream

### PR DESCRIPTION
**Pull request by graphemecluster**
Or if you don’t like it, we can put these workflow steps in the downstream repo instead, like what we’ve done in rime-cantonese: https://github.com/rime/rime-cantonese/blob/main/.github/workflows/fetch-upstream.yml

### CODE REVIEW

**Comment by bingzheung** [comment]
Hi @graphemecluster 

我唔係幾熟悉 CI 啲嘢，你揸主意啦。

可能係由下游定期 fetch 好啲，呢個倉庫我會改得比較隨意，好多改動會與 rime emoji 無關。

**Comment by graphemecluster** [comment]
CI 可以改成淨係喺 `*emoji*.txt` 有修改嗰陣先行嘅，你認為點？
我只係覺得啲 artifact commit 出嚟放落同一個 repo 唔係咁好，破壞咗專登分開做兩個 repo 嘅原意，不過都冇乜大礙嘅。
又或者可以由下游重新行 generation 嘅 command，但係噉個 toolchain 會重複咗

**Comment by bingzheung** [comment]
> CI 可以改成淨係喺 `*emoji*.txt` 有修改嗰陣先行嘅，你認為點？

可唔可以改成，新增一個 file 例如 `opencc/emoji-generated.txt` ，當佢有修改時再更新下游。
因為嗰啲 `*-emoji-*.txt` 一樣會經常改，唔穩定。

**Comment by graphemecluster** [comment]
唔緊要，我下游 fetch 啦

**Pull request closed without merging**
